version: "3"

services:
  anki_node:
    container_name: anki_node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - "MONGODB_URL=mongodb://mongodb:27017/anki_database"
      - "MONGO_USERNAME=root"
      - "MONGO_PASSWORD=example"
      - "PORT=8080"
    command: ["npm", "start"]

  mongodb:
    container_name: mongodb
    image: mongo:4.2.2-bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
