version: "3"

services:
  anki_node:
    container_name: anki_node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "MONGODB_URL=mongodb+srv://admin:5ik1yrkSUOUOYId4@anki-cards-gjj6q.mongodb.net/test?retryWrites=true&w=majority"
      - "MONGO_USERNAME=admin"
      - "MONGO_PASSWORD=5ik1yrkSUOUOYId4"
      - "PORT=8080"
      - "JWT_SECRET=thisisasamplesecret"
      - "JWT_ACCESS_EXPIRATION_MINUTES=30"
      - "JWT_REFRESH_EXPIRATION_DAYS=30"
      - "SMTP_HOST=smtp.ethereal.email"
      - "SMTP_PORT=587"
      - "SMTP_USERNAME=morris.oconner67@ethereal.email"
      - "SMTP_PASSWORD=nyHNRAyUvfEg9UMsWR"
      - "EMAIL_FROM=support@ankiapp.com"
    command: ["npm", "start"]

  mongodb:
    container_name: mongodb
    image: mongo:4.2.2-bionic
    restart: always
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
